apiVersion: batch/v1
kind: Job
metadata:
  name: windows-image-pull
  namespace: openshift-windows-machine-config-operator
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/ssh/private-key.pem administrator@ip-10-0-144-235.us-east-2.compute.internal docker pull quay.io/donschenck/netcandystore:2021feb2.1
        image: quay.io/redhatworkshops/winc-ssh:latest
        name: windows-image-pull
        volumeMounts:
        - name: sshkey
          mountPath: "/tmp/ssh"
          readOnly: true
        resources: {}
      volumes:
      - name: sshkey
        secret:
          secretName: cloud-private-key
          defaultMode: 0400
